name: Latest Blog Posts Workflow

on:
  schedule:
    - cron: '0 * * * *'  # Updates every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get latest posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_url: "https://dev.to/feed/deepzsenu"  # Change to your feed URL

      - name: Update README with latest posts
        run: |
          git config --local user.email "youremail@example.com"
          git config --local user.name "Deepak Saxena"
          git add README.md
          git commit -m "Updated latest blog posts"
          git push
