name: Count Lines of Code

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday

jobs:
  loc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Install cloc
        run: sudo apt-get install cloc

      - name: Count lines of code
        run: cloc --json . > cloc-report.json

      - name: Add to README
        run: |
          loc=$(jq '.SUM.code' cloc-report.json)
          echo "Total lines of code in this repo: $loc" >> README.md
          git config --global user.email "youremail@example.com"
          git config --global user.name "Deepak Saxena"
          git add README.md
          git commit -m "Update lines of code"
          git push
