name: Update Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Update daily at midnight
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Step 2: Get the lines of code and commit count
      - name: Get Lines of Code and Commits
        run: |
          total_loc=$(git ls-files | xargs wc -l | grep total | awk '{print $1}')
          total_commits=$(git rev-list --all --count)
          echo "Total Lines of Code: $total_loc" > stats.txt
          echo "Total Commits: $total_commits" >> stats.txt

      # Step 3: Update the README file
      - name: Update README
        run: |
          loc=$(grep 'Total Lines of Code' stats.txt | awk '{print $5}')
          commits=$(grep 'Total Commits' stats.txt | awk '{print $3}')
          
          # Replace placeholders with the updated values
          sed -i "s/<!--TOTAL_LINES_OF_CODE-->/Total Lines of Code: $loc/" README.md
          sed -i "s/<!--TOTAL_COMMITS-->/Total Commits: $commits/" README.md

      # Step 4: Commit and push the changes
      - name: Commit and Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest stats"
          git push https://$GH_TOKEN@github.com/deepzsenu/deepzsenu.git HEAD:master
